# Generated by Django 4.2.7 on 2023-12-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_model',
            name='gender',
            field=models.CharField(choices=[['Male', 'Male'], ['Female', 'Female'], ['other', 'other']], max_length=10),
        ),
    ]
