# Generated by Django 5.0 on 2023-12-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_category',
            new_name='category_items',
        ),
        migrations.RenameModel(
            old_name='category_item',
            new_name='product_item',
        ),
    ]
