# Generated by Django 4.2.7 on 2023-12-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_model',
            name='cust_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy_model',
            name='item_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
