# Generated by Django 4.2.7 on 2023-12-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_app', '0002_buy_model_cust_id_buy_model_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy_model',
            name='t_price',
        ),
    ]
