# Generated by Django 4.2.7 on 2023-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_app', '0004_buyed_item_list_remove_buy_model_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_model',
            name='cust_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy_model',
            name='cust_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy_model',
            name='cust_phone',
            field=models.PositiveBigIntegerField(default=64254),
            preserve_default=False,
        ),
    ]
