# Generated by Django 4.2.7 on 2023-12-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_app', '0005_buy_model_cust_address_buy_model_cust_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_model',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
    ]
