# Generated by Django 4.2.7 on 2023-12-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_model_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_model',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
