# Generated by Django 4.2.7 on 2023-12-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_model_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_model',
            name='item_name',
            field=models.CharField(default='apple', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_model',
            name='price',
            field=models.PositiveIntegerField(default=80),
            preserve_default=False,
        ),
    ]
